import { apiSlice } from '@/app/apiSlice';

export interface Settings {
  organizationName: string;
  timezone: string;
  language: string;
  theme: 'light' | 'dark' | 'system';
  brandColor: string;
  geminiApiKey: string;
  aiModel: string;
  aiTemperature: number;
  pdfPaperSize: 'A4' | 'Letter';
  pdfOrientation: 'Portrait' | 'Landscape';
  pdfIncludeImage: boolean;
  pdfIncludeAi: boolean;
  pdfHeaderLogo: string;
  pdfFooterText: string;
}

const defaultSettings: Settings = {
  organizationName: 'Acme Corp',
  timezone: 'UTC',
  language: 'en',
  theme: 'light',
  brandColor: '#4f46e5',
  geminiApiKey: '',
  aiModel: 'gemini-1.5-flash',
  aiTemperature: 0.7,
  pdfPaperSize: 'A4',
  pdfOrientation: 'Portrait',
  pdfIncludeImage: true,
  pdfIncludeAi: true,
  pdfHeaderLogo: '',
  pdfFooterText: 'Generated by Ofference Events',
};

const getLocalSettings = (): Settings => {
  const stored = localStorage.getItem('eventpro_settings');
  if (stored) {
    return { ...defaultSettings, ...JSON.parse(stored) };
  }
  return defaultSettings;
};

export const settingsApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    getSettings: builder.query<Settings, void>({
      queryFn: () => {
        return { data: getLocalSettings() };
      },
      providesTags: ['Settings'],
    }),
    updateSettings: builder.mutation<Settings, Partial<Settings>>({
      queryFn: (newSettings) => {
        const current = getLocalSettings();
        const updated = { ...current, ...newSettings };
        localStorage.setItem('eventpro_settings', JSON.stringify(updated));
        
        // Handle theme update immediately for smooth UX
        if (newSettings.theme) {
           // The ThemeProvider typically listens to local storage or state
           // but we'll let the app handle it via useGetSettingsQuery
        }

        return { data: updated };
      },
      invalidatesTags: ['Settings'],
    }),
  }),
});

export const { useGetSettingsQuery, useUpdateSettingsMutation } = settingsApi;
